### ISSUE TITLE
Way to custom your "Contrast" theme for Jekyll

### ISSUE THREAD

**Issue by mmni** [niklasbuschmann/contrast#1]
Hello there,

I recently start to self-learning Jekyll related stuff, and I found your theme looks good. I forked it and tried to use it as the starting point of my personal page in github. 

As a completely beginner, it would be very helpful, if you can show me some hints (or give me some pointers) about how I can custom the current looking of the "Contrast" theme (I think I have already know how to handle the content part). Does that related to the "sass" part in the repository? 

Thank you so much.

**Comment by niklasbuschmann** [comment]
You can customize some aspects of the theme in the *style* section of the *config.yml*.

Or you can customize the [sass](http://sass-lang.com/) (which is compiled to css) in the *_sass* folder.
