### ISSUE TITLE
mailto:"your-email-address@email.com" tab doesn't open upon clicking the mail icon

### ISSUE THREAD

**Issue by davidglavas** [niklasbuschmann/contrast#1]
On my phone the mail app opens upon clicking the mail icon whereas on my pc nothing happens (using Chrome Version 63.0.3239.132).

The mailto tab opens when clicking on the mail icon and selecting the "open in new tab", would be nice if it opened with a simple left click of the mouse.

**Comment by niklasbuschmann** [comment]
This is browser specific and can't be fixed in the theme.
