### ISSUE TITLE
Update README.md to suggest commit pinning

### ISSUE THREAD

**Issue by eyjohn** [niklasbuschmann/contrast#13]
Firstly, thanks for this great theme!

Unfortunately, while I was setting up my CD pipeline to automatically deploy this theme using the advertised remote-theme method. My builds started to break a (or rather look wrong) as they started using the latest version of your master which is very much evolving.

I suggest advising users to pin their remote theme to a specific git version (or perhaps even releases/tags if you prefer). Perhaps it would be great to include it here:
https://github.com/niklasbuschmann/contrast#installation-jekyll-remote-theme-method

Thanks

**Comment by niklasbuschmann** [comment]
Done 👍

Thanks for the suggestion!
