### ISSUE TITLE
Images not supported with url

### ISSUE THREAD

**Issue by sbd** [niklasbuschmann/contrast#16]
If I navigate to _posts/ in Github I can see the image I'm trying to display in my post but if I go to my deployed static github page, the image appears broken. I've tried jpg and png formats but the following markdown isn't working: 

```
![500 Error](https://github.com/sbd/sbd.github.io/blob/master/assets/gremlin-shutdown-attack.jpg)
```

Only this worked:
```
![500 Error](/assets/gremlin-shutdown-attack.jpg)
```

**Comment by niklasbuschmann** [comment]
Have you tried changing the link
`https://github.com/sbd/sbd.github.io/blob/master/assets/gremlin-shutdown-attack.jpg` to
`https://raw.githubusercontent.com/sbd/sbd.github.io/master/assets/gremlin-shutdown-attack.jpg`?

Despite ending in .jpg the first one is just plain html with the image embedded in it.

**Comment by sbd** [comment]
Touché that works too, thanks!
