### ISSUE TITLE
Wrong title in 404 page

### ISSUE THREAD

**Issue by mrcat323** [niklasbuschmann/contrast#17]
Hey, nice job, template is nice though, but I caught a __bug__ here, wrong title in 404 page, so here is the page
![image](https://user-images.githubusercontent.com/23054662/72979550-6727c780-3dfa-11ea-809a-93ab31d63c13.png)
And here is the **title**:
![image](https://user-images.githubusercontent.com/23054662/72979596-81fa3c00-3dfa-11ea-8a69-a9ab32f10433.png)

**Comment by niklasbuschmann** [comment]
Thanks!

Fixed by https://github.com/niklasbuschmann/contrast/commit/22359f5eff05c4c2fac11dcfa8cdee43e52087c4
