### ISSUE TITLE
footer shadow, alignment, size issue

### ISSUE THREAD

**Issue by bahnfrei** [niklasbuschmann/contrast#18]
Hi Niklas,

great work! i like the revised theme and have done some tests with the latest version. maybe you can have a look at the following issue i found (see attached screenshot)?

it seems that in some cases the footer doesn't fit the whole width and isn't placed correctly for short posts. i'd like to suggest you to move the footer to the bottom in any case or remove the shadow at the bottom.

Thanks, Michi.

**Comment by bahnfrei** [comment]
![footer-issue](https://user-images.githubusercontent.com/10193241/73058698-6e9baf00-3e94-11ea-8bc7-b2f6a50afd2d.png)

**Comment by bahnfrei** [comment]
ok, the problem does not only affect the footer ;-) the entire body width doesn't seem to grow beyond 1080px, for whatever reason...

**Comment by bahnfrei** [comment]
sorry, didn't pull the latest commits yesterday. the article placement looks much better now, but i miss the footer with the navigation (prev/next post) :-( found this kind of navigation really useful...

**Comment by niklasbuschmann** [comment]
Hello Michi,

I recently added the option `show_related` which replaces the `show_footer` option, I hope this is a viable alternative for you. See it [in action](https://niklasbuschmann.github.io/contrast/welcome-to-jekyll/).

I hope I fixed all existing layout issues, otherwise let me know.

And thanks for your feeback!

**Comment by bahnfrei** [comment]
Hi Niklas,

thank you for your answer and for taking my comments into account. i already tested the first draft yesterday evening... i really like the improved alignment of the prev/next links now. i think i can live with that ;-) thanks a lot! great work!

Michi
