### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by rjopek** [niklasbuschmann/contrast#19]
Hi,

I have a build error

Liquid Exception: Liquid syntax error (line 37): Unknown tag 'gist' in contrast-master/_posts/2017-01-01-advanced-examples.md

-- Rafał

**Comment by yagarea** [comment]
@rjopek Please can you share how you fixed this issue ?

**Comment by rjopek** [comment]
Hi,

I have not solved this build problem, just closed this information.

-- Rafał

**Comment by niklasbuschmann** [comment]
The problem should be solved with v2.2
