### ISSUE TITLE
Sytax hilighting not support objective-c

### ISSUE THREAD

**Issue by skx926** [niklasbuschmann/contrast#2]
Sytax hilighting not support objective-c

**Comment by niklasbuschmann** [comment]
Jekyll uses Pygments as syntax highlighter, so Objective-C [should be supported](http://pygments.org/languages/).

Are you using the [jekyll code highlighting syntax](http://jekyllrb.com/docs/templates/#code-snippet-highlighting)?

Should look like this:
```
{% highlight objective-c %}
// your code here
{% endhighlight %}
```
