### ISSUE TITLE
footer config option breaks post navigation

### ISSUE THREAD

**Issue by bahnfrei** [niklasbuschmann/contrast#21]
Hi Niklas,

the newly introduced footer config option breaks the post navigation. Maybe you can verify that and fix it? This also happens, when footer links are enabled the sidebar is enabled as well...

Best regards, Michi.

**Comment by niklasbuschmann** [comment]
Thanks, turns out the footer was to fiddly so I decided to revert the commits altogether.

I don’t plan on any changes in the near future so the repo should stay somewhat stable now.

**Comment by bahnfrei** [comment]
Thanks! And yes, sometimes it's adding by subtracting... ;-)
