### ISSUE TITLE
Add pagination in home & archive

### ISSUE THREAD

**Issue by kenmux** [niklasbuschmann/contrast#5]
I like this theme, and just want to use it in my blog, but there's a problem: there's no pagination. 
You see, if there are lots of posts, and the home & archive page will be very very long. I wonder, can this theme be supported for pagination, just as other themes do?

**Comment by niklasbuschmann** [comment]
If it doesn't take too much effort to implement pagination, I will try to support it.

**Comment by niklasbuschmann** [comment]
Pagination should now be supported, see my homepage as an [example](http://niklabs.me/page2/).

If there should be any bugs, feel free to report them.

**Comment by kenmux** [comment]
Thanks, I'm looking into it! Good job, anyway!
