### ISSUE TITLE
Is this a spelling mistake?

### ISSUE THREAD

**Issue by kenmux** [niklasbuschmann/contrast#6]
In the file _layouts/default.html, line 6, there's a variable 'site.baseur' never saw anywhere else, do you mean 'site.baseurl'?

**Comment by niklasbuschmann** [comment]
Yeah, this [was](https://github.com/niklasbuschmann/contrast/commit/8c682a1cc9bfe7091fc8d9b9e4ef5f7f335b46f6) a typing error.

Thanks for reporting.
