### ISSUE TITLE
Missing <head> tag

### ISSUE THREAD

**Issue by ColinWaddell** [niklasbuschmann/contrast#6]
Hey, great work on the theme. Started using it on [my blog](https://blog.colinwaddell.com) last night and it's been perfect :+1: 

One thing I did notice is that there appears to be no `<head>` tag wrapping the site's metadata/imports etc.

Thought I'd flag it in case it's just been overlooked.

All the best,
Colin

**Comment by niklasbuschmann** [comment]
Hello Colin,

I'm glad you like my theme. Since both the head and body tag are optional (and some even [recommend omitting them](https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags) I decided to leave out the <head> tag.

But thanks for the notice 👍
