### ISSUE TITLE
excerpt not working

### ISSUE THREAD

**Issue by sigul** [niklasbuschmann/contrast#7]
Hi, 
or I can't figure out how excerpt works, or it doesn't work. 

I couldn't find any /n/n/n block in the example posts, nor jekyll take the first p.
I tried to use a different excerpt_separator but it didn't work

**Comment by kenmux** [comment]
Hello! I think you'd try "", for me, it works charming!

**Comment by sigul** [comment]
solved: I don't know how, <-!more-> works. essentially,  is commented out and not displayed, while any other "more" is displayed as text

**Comment by kenmux** [comment]
For my test, both "\n\n\n" and  be fine; but, at one time, only the later one takes work!
In my opinion, you may mistake the number of "\n"...you should add extra 3 "\n" after the paragraph be displayed, the ones to split paragraph cannot be counted in!

**Comment by sigul** [comment]
actually, when displaying the post page the tag <-!more-> is shown and not hided. 
the only customization I did was to remove this 

article:nth-of-type(even)
    +article_background($even, $anchor)

article:nth-of-type(odd)
    +article_background($odd, $anchor)

to avoid the black alternate background in home.

@kenmux didn't get what you mean. I used /n/n/n as a separator.

**Comment by kenmux** [comment]
You say "/n/n/n"? not "\n\n\n"? Sorry, I misunderstand it, my fault! :(

**Comment by sigul** [comment]
shame on me! I didn't know /n/n/n stand for enter*3.

In any case, Jekyll documentation says you can use a specific tag like <!-more->, but it doesn't work in this theme

**Comment by kenmux** [comment]
@sigul 
No, I can only see the use of ; refer to this: http://jekyllrb.com/docs/posts/, and search with key word "excerpt".
And, I suggest you use the format , while "KEY" is the custom string you like! In fact, for html syntax, the string in the pair of "" is comment, that's why you cannot see it when clicking "read more"!

**Comment by niklasbuschmann** [comment]
The jekyll mechanism for post excerpts is independent from the theme, in the [default configuration](http://jekyllrb.com/docs/configuration/#default-configuration) they use two newlines (*excerpt_separator: "\n\n"*) so the excerpt is automatically the first paragraph.

I changed it to three newlines so I can select the paragraph after which the excerpt ends, but this is just personal preference.

If you want to use any other seperator add the HTML comment tag (**), so you won't see it in the full article.

**Comment by sigul** [comment]
got it, thanks!
