### ISSUE TITLE
bold text is not rendered correctly

### ISSUE THREAD

**Issue by bahnfrei** [niklasbuschmann/contrast#9]
Hi Niklas,

while putting the new version into production i recognised, that **bold text** doesn't differ from the normal one :-( maybe the standard font-weight has to be adjusted a little bit?

Best regards, Michi.

**Comment by bahnfrei** [comment]
It seems this effect depends on different screen resolution, browser, operating system.

- Firefox, Chrome on Samsung Galaxy S5 Android 7 works as expected
- Firefox, Chrome, Safari on macOS Mojave, LG external Display (3440 x 1440) with different browser window sizes shows only a small difference between bold and normal text
- Firefox, Chrome on Arch Linux, full HD (1920 x 1080) with different browser window sizes shows no difference between bold and normal text

**Comment by niklasbuschmann** [comment]
Thanks Michi for pointing this out - and sorry for my late response.

The fonts weights are now set to 400 (normal) and 600 (bold), this should fix the issue.

I think there should be a noticeable difference between 400 and 600 on the default fonts for every OS, but feel free to reopen if the issue persists.
